### ISSUE TITLE
Logger middleware does not work as expectation

### ISSUE THREAD

**Issue by ansidev** [gofiber/docs#214] opened 2021-11-12 02:46 UTC
1. 
Config
```go
app.Use(logger.New(logger.Config{
	Format:     "[${pid}]:${port} ${status} - ${method} ${path}\n",
	TimeFormat: "2006-01-02T15:04:05.0Z",
	TimeZone:   "Asia/Ho_Chi_Minh",
}))
```
Output
```
2021-11-12T09:29:26.4Z | 200 |      0s |       127.0.0.1 | GET     | /hello
```
2.
Config
```go
app.Use(logger.New(logger.Config{
        Format:     "[${ip}]:${port} ${status} - ${method} ${path}\n",
}))
```
Output
```
09:44:28 | 200 |      0s |       127.0.0.1 | GET     | /hello
```

I think this is a bug! Did I miss something?

**Comment by ReneWerner87** [comment] 2021-11-12 07:29
Duplicate of [#1609](https://github.com/gofiber/fiber/issues/1609)

**Closed by ReneWerner87** 2021-11-12 07:29 UTC
